name: Project Build and Test
# https://github.com/sbt/setup-sbt

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      JAVA_OPTS: "-Xms2048M -Xmx2048M -Xss6M -XX:ReservedCodeCacheSize=256M -Dfile.encoding=UTF-8"

    steps:
      - name: Checkout Current Repo
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'

      - name: Install SBT
        uses: sbt/setup-sbt@v1

      - name: Build and test
#        env:
#          _JAVA_OPTIONS: "-Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw"
        shell: bash
        run: sbt -v +test